import * as React from "react"
import type { HeadFC } from "gatsby"
import NavigationBar from '../components/navigationbar'
import Container from 'react-bootstrap/Container';

export default class IndexPage extends React.Component {
  render() {
    return (
      <div>
        <NavigationBar></NavigationBar>
        <Container>
          hehe in about
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Viverra vitae congue eu consequat. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Maecenas pharetra convallis posuere morbi leo. Non enim praesent elementum facilisis leo. Ultrices dui sapien eget mi proin sed libero enim. Risus feugiat in ante metus dictum at. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Feugiat in ante metus dictum at. Vitae turpis massa sed elementum tempus egestas sed. Parturient montes nascetur ridiculus mus mauris vitae. Porttitor leo a diam sollicitudin. Condimentum id venenatis a condimentum vitae.

          Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Turpis nunc eget lorem dolor sed viverra ipsum nunc. In vitae turpis massa sed elementum tempus egestas sed. Nec feugiat in fermentum posuere urna nec tincidunt. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Felis imperdiet proin fermentum leo vel orci porta. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Suscipit tellus mauris a diam maecenas sed enim. Iaculis nunc sed augue lacus viverra vitae congue eu. Aenean sed adipiscing diam donec adipiscing.

          Auctor urna nunc id cursus metus aliquam eleifend mi in. Ut tortor pretium viverra suspendisse potenti. Tristique sollicitudin nibh sit amet commodo. Faucibus pulvinar elementum integer enim neque. Nunc sed velit dignissim sodales ut eu sem. Ac turpis egestas maecenas pharetra. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Libero volutpat sed cras ornare arcu dui vivamus arcu. Volutpat est velit egestas dui id. Orci ac auctor augue mauris augue neque gravida. Vitae tortor condimentum lacinia quis vel. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Viverra tellus in hac habitasse platea.

          Adipiscing elit pellentesque habitant morbi tristique senectus et. Amet nisl purus in mollis nunc sed. Congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tortor aliquam nulla facilisi cras fermentum odio. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Turpis egestas integer eget aliquet nibh praesent tristique magna. Fringilla est ullamcorper eget nulla. Elementum sagittis vitae et leo duis ut diam quam. In egestas erat imperdiet sed euismod nisi porta lorem. Nibh cras pulvinar mattis nunc sed blandit. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Nibh praesent tristique magna sit amet purus gravida. Aliquet lectus proin nibh nisl. Ante metus dictum at tempor commodo ullamcorper. Turpis massa tincidunt dui ut ornare lectus sit. Rhoncus urna neque viverra justo nec ultrices dui sapien eget.

          Ac odio tempor orci dapibus ultrices in. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Vestibulum sed arcu non odio euismod. Morbi blandit cursus risus at ultrices mi tempus. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Adipiscing enim eu turpis egestas pretium. Non diam phasellus vestibulum lorem sed. Praesent elementum facilisis leo vel fringilla est ullamcorper. Risus at ultrices mi tempus imperdiet. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. In ante metus dictum at tempor commodo. Purus in mollis nunc sed id semper risus. Quisque non tellus orci ac auctor. Duis at tellus at urna condimentum. Urna condimentum mattis pellentesque id. At varius vel pharetra vel. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Viverra vitae congue eu consequat. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Maecenas pharetra convallis posuere morbi leo. Non enim praesent elementum facilisis leo. Ultrices dui sapien eget mi proin sed libero enim. Risus feugiat in ante metus dictum at. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Feugiat in ante metus dictum at. Vitae turpis massa sed elementum tempus egestas sed. Parturient montes nascetur ridiculus mus mauris vitae. Porttitor leo a diam sollicitudin. Condimentum id venenatis a condimentum vitae.

Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Turpis nunc eget lorem dolor sed viverra ipsum nunc. In vitae turpis massa sed elementum tempus egestas sed. Nec feugiat in fermentum posuere urna nec tincidunt. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Felis imperdiet proin fermentum leo vel orci porta. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Suscipit tellus mauris a diam maecenas sed enim. Iaculis nunc sed augue lacus viverra vitae congue eu. Aenean sed adipiscing diam donec adipiscing.

Auctor urna nunc id cursus metus aliquam eleifend mi in. Ut tortor pretium viverra suspendisse potenti. Tristique sollicitudin nibh sit amet commodo. Faucibus pulvinar elementum integer enim neque. Nunc sed velit dignissim sodales ut eu sem. Ac turpis egestas maecenas pharetra. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Libero volutpat sed cras ornare arcu dui vivamus arcu. Volutpat est velit egestas dui id. Orci ac auctor augue mauris augue neque gravida. Vitae tortor condimentum lacinia quis vel. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Viverra tellus in hac habitasse platea.

Adipiscing elit pellentesque habitant morbi tristique senectus et. Amet nisl purus in mollis nunc sed. Congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tortor aliquam nulla facilisi cras fermentum odio. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Turpis egestas integer eget aliquet nibh praesent tristique magna. Fringilla est ullamcorper eget nulla. Elementum sagittis vitae et leo duis ut diam quam. In egestas erat imperdiet sed euismod nisi porta lorem. Nibh cras pulvinar mattis nunc sed blandit. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Nibh praesent tristique magna sit amet purus gravida. Aliquet lectus proin nibh nisl. Ante metus dictum at tempor commodo ullamcorper. Turpis massa tincidunt dui ut ornare lectus sit. Rhoncus urna neque viverra justo nec ultrices dui sapien eget.

Ac odio tempor orci dapibus ultrices in. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Vestibulum sed arcu non odio euismod. Morbi blandit cursus risus at ultrices mi tempus. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Adipiscing enim eu turpis egestas pretium. Non diam phasellus vestibulum lorem sed. Praesent elementum facilisis leo vel fringilla est ullamcorper. Risus at ultrices mi tempus imperdiet. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. In ante metus dictum at tempor commodo. Purus in mollis nunc sed id semper risus. Quisque non tellus orci ac auctor. Duis at tellus at urna condimentum. Urna condimentum mattis pellentesque id. At varius vel pharetra vel. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Viverra vitae congue eu consequat. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Maecenas pharetra convallis posuere morbi leo. Non enim praesent elementum facilisis leo. Ultrices dui sapien eget mi proin sed libero enim. Risus feugiat in ante metus dictum at. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Feugiat in ante metus dictum at. Vitae turpis massa sed elementum tempus egestas sed. Parturient montes nascetur ridiculus mus mauris vitae. Porttitor leo a diam sollicitudin. Condimentum id venenatis a condimentum vitae.

          Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Turpis nunc eget lorem dolor sed viverra ipsum nunc. In vitae turpis massa sed elementum tempus egestas sed. Nec feugiat in fermentum posuere urna nec tincidunt. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Felis imperdiet proin fermentum leo vel orci porta. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Suscipit tellus mauris a diam maecenas sed enim. Iaculis nunc sed augue lacus viverra vitae congue eu. Aenean sed adipiscing diam donec adipiscing.

          Auctor urna nunc id cursus metus aliquam eleifend mi in. Ut tortor pretium viverra suspendisse potenti. Tristique sollicitudin nibh sit amet commodo. Faucibus pulvinar elementum integer enim neque. Nunc sed velit dignissim sodales ut eu sem. Ac turpis egestas maecenas pharetra. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Libero volutpat sed cras ornare arcu dui vivamus arcu. Volutpat est velit egestas dui id. Orci ac auctor augue mauris augue neque gravida. Vitae tortor condimentum lacinia quis vel. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Viverra tellus in hac habitasse platea.

          Adipiscing elit pellentesque habitant morbi tristique senectus et. Amet nisl purus in mollis nunc sed. Congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tortor aliquam nulla facilisi cras fermentum odio. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Turpis egestas integer eget aliquet nibh praesent tristique magna. Fringilla est ullamcorper eget nulla. Elementum sagittis vitae et leo duis ut diam quam. In egestas erat imperdiet sed euismod nisi porta lorem. Nibh cras pulvinar mattis nunc sed blandit. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Nibh praesent tristique magna sit amet purus gravida. Aliquet lectus proin nibh nisl. Ante metus dictum at tempor commodo ullamcorper. Turpis massa tincidunt dui ut ornare lectus sit. Rhoncus urna neque viverra justo nec ultrices dui sapien eget.

          Ac odio tempor orci dapibus ultrices in. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Vestibulum sed arcu non odio euismod. Morbi blandit cursus risus at ultrices mi tempus. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Adipiscing enim eu turpis egestas pretium. Non diam phasellus vestibulum lorem sed. Praesent elementum facilisis leo vel fringilla est ullamcorper. Risus at ultrices mi tempus imperdiet. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. In ante metus dictum at tempor commodo. Purus in mollis nunc sed id semper risus. Quisque non tellus orci ac auctor. Duis at tellus at urna condimentum. Urna condimentum mattis pellentesque id. At varius vel pharetra vel. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet.

        </Container>

      </div>
    );
  }
}

export const Head: HeadFC = () => <title>Home Page</title>
